#/etc/kubernetes/manifests/kubeadm-node-config.yaml

apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    # your join token. E.g. 5didvk.d09sbcov8ph2amjw
    token: <token>
    # your control-plane API server ip and port. E.g. 172.31.38.150:6443
    apiServerEndpoint: <api server (see in kube config file)>
    caCertHashes:
      #token ca cert hash. e.g. sha256:aced39939a479d2fe513f96dbc7c7030f0b2e04fa82b4d37314446a2d05e721a
      - <ca cert>
nodeRegistration:
  #your instance hostname. E.g. ip-172-31-42-153.us-east-1.compute.internal
  name: <ec2 hostname>
  kubeletExtraArgs:
    cloud-provider: external


#type the command to join the node to the cluster with the manifest
#sudo kubeadm join --config kubeadm-node-config.yaml