apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-down-time-dep
  labels:
    app: zero-down-time
spec:
  selector:
    matchLabels:
      app: zero-down-time
  template:
    metadata:
        labels:
          app: zero-down-time
    spec:
      containers:
      - name: nodejs-server
        image: orrmb/zero_down_time:latest
        resources:
          requests:
            cpu: 300m
          limits:
            cpu: 300m
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 3000
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/ready"
            port: 3000
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: srv-zero-down-time
spec:
  selector:
    app:  zero-down-time
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
---