apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolobot-dep
  labels:
    app: yolobot-app
spec:
  selector:
    matchLabels:
      app: yolobot
  template:
    metadata:
        labels:
          app: yolobot
    spec:
      containers:
      - name: yolo-app
        image: orrmb/yolo-app:k8s
        resources:
          requests:
            cpu: 300m
          limits:
            cpu: 300m
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 3000
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/ready"
            port: 3000
        lifecycle:
          preStop:
            exec:
              command: []

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscale-yolobot-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolobot-dep
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

  #kubectl apply -f yolobot.yaml --namespace=bot-yolo-app